### ISSUE TITLE
Maven install fails - project structure

### ISSUE THREAD

**Issue by fletchgqc** [HotswapProjects/HotswapAgentExamples#14]
Hi, this feels like a stupid question but I can't do anything with this project. Maven complains about the project structure. See the following output after I cloned the project:

(Maven 3.3.3 on Java 7)

C:\dev\HotswapAgentExamples>mvn install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version
] (C:\dev\HotswapAgentExamples\hotswap-agent-examples-servlet-parent\pom.xml) points at org.hotswap.agent:hotswap-ag
ent-examples-aggregator instead of org.hotswap.agent:hotswap-agent-parent, please verify your project structure @ line 5
, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version]
: Could not find artifact org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points at
wrong local POM @ line 5, column 13
[WARNING] 'parent.relativePath' of POM org.hotswap.examples:plain-java:[unknown-version] (C:\dev\HotswapAgentExample
s\plain-java\pom.xml) points at org.hotswap.agent:hotswap-agent-examples-aggregator instead of org.hotswap.agent:hotswap
-agent-parent, please verify your project structure @ line 7, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.examples:plain-java:[unknown-version]: Could not find artifact org.hot
swap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column
13
[WARNING] 'parent.relativePath' of POM org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version
] (C:\dev\HotswapAgentExamples\hotswap-agent-examples-servlet-parent\pom.xml) points at org.hotswap.agent:hotswap-ag
ent-examples-aggregator instead of org.hotswap.agent:hotswap-agent-parent, please verify your project structure @ org.ho
tswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version], C:\dev\HotswapAgentExamples\hotswap-ag
ent-examples-servlet-parent\pom.xml, line 5, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version]
: Could not find artifact org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points at
wrong local POM @ org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version], C:\dev\Hotswap
AgentExamples\hotswap-agent-examples-servlet-parent\pom.xml, line 5, column 13
[WARNING] 'parent.relativePath' of POM org.hotswap.plugin.examples:custom-plugin:[unknown-version] (C:\dev\HotswapAg
entExamples\custom-plugin\pom.xml) points at org.hotswap.agent:hotswap-agent-examples-aggregator instead of org.hotswap.
agent:hotswap-agent-parent, please verify your project structure @ line 7, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.plugin.examples:custom-plugin:[unknown-version]: Could not find artifa
ct org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line
7, column 13
[WARNING] 'parent.relativePath' of POM org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version
] (C:\dev\HotswapAgentExamples\hotswap-agent-examples-servlet-parent\pom.xml) points at org.hotswap.agent:hotswap-ag
ent-examples-aggregator instead of org.hotswap.agent:hotswap-agent-parent, please verify your project structure @ org.ho
tswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version], C:\dev\HotswapAgentExamples\hotswap-ag
ent-examples-servlet-parent\pom.xml, line 5, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version]
: Could not find artifact org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points at
wrong local POM @ org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version], C:\dev\Hotswap
AgentExamples\hotswap-agent-examples-servlet-parent\pom.xml, line 5, column 13
[WARNING] 'parent.relativePath' of POM org.hotswap.examples:seam-hibernate-jsf:[unknown-version] (C:\dev\HotswapAgen
tExamples\seam-hibernate-jsf\pom.xml) points at org.hotswap.agent:hotswap-agent-examples-aggregator instead of org.hotsw
ap.agent:hotswap-agent-parent, please verify your project structure @ line 6, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.examples:seam-hibernate-jsf:[unknown-version]: Failure to find org.hot
swap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT in http://snapshots.jboss.org/maven2/ was cached in the local reposit
ory, resolution will not be reattempted until the update interval of snapshots.jboss.org has elapsed or updates are forc
ed and 'parent.relativePath' points at wrong local POM @ line 6, column 13
[WARNING] 'parent.relativePath' of POM org.hotswap.examples:cdi-hibernate-jsf:[unknown-version] (C:\dev\HotswapAgent
Examples\cdi-hibernate-jsf\pom.xml) points at org.hotswap.agent:hotswap-agent-examples-aggregator instead of org.hotswap
.agent:hotswap-agent-parent, please verify your project structure @ line 6, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.examples:cdi-hibernate-jsf:[unknown-version]: Could not find artifact
org.hotswap.agent:hotswap-agent-parent:pom:0.3.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6,
column 13
[WARNING] 'parent.relativePath' of POM org.hotswap.examples:ejb-cdi-hibernate-jsf:[unknown-version] (C:\dev\HotswapA
gentExamples\ejb-cdi-hibernate-jsf\pom.xml) points at org.hotswap.agent:hotswap-agent-examples-aggregator instead of org
.hotswap.agent:hotswap-agent-parent, please verify your project structure @ line 6, column 13
[FATAL] Non-resolvable parent POM for org.hotswap.examples:ejb-cdi-hibernate-jsf:[unknown-version]: Failure to find org.
hotswap.agent:hotswap-agent-parent:pom:0.3.0-SNAPSHOT in https://repository.jboss.org/nexus/content/groups/public/ was c
ached in the local repository, resolution will not be reattempted until the update interval of JBoss Repository has elap
sed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 13
 @
[ERROR] The build could not read 8 projects -> [Help 1]
[ERROR]
[ERROR]   The project org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version] (C:\dev\Hot
swapAgentExamples\hotswap-agent-examples-servlet-parent\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-vers
ion]: Could not find artifact org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points
 at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.hotswap.examples:plain-java:[unknown-version] (C:\dev\HotswapAgentExamples\plain-java\pom.
xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.examples:plain-java:[unknown-version]: Could not find artifact org
.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, col
umn 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.hotswap.examples:plain-servlet:[unknown-version] (C:\dev\HotswapAgentExamples\plain-servle
t\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-vers
ion]: Could not find artifact org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points
 at wrong local POM @ org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version], C:\dev\Hot
swapAgentExamples\hotswap-agent-examples-servlet-parent\pom.xml, line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.hotswap.plugin.examples:custom-plugin:[unknown-version] (C:\dev\HotswapAgentExamples\custo
m-plugin\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.plugin.examples:custom-plugin:[unknown-version]: Could not find ar
tifact org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ l
ine 7, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.hotswap.examples:spring-hibernate:[unknown-version] (C:\dev\HotswapAgentExamples\spring-hi
bernate\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-vers
ion]: Could not find artifact org.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT and 'parent.relativePath' points
 at wrong local POM @ org.hotswap.agent.examples:hotswap-agent-examples-servlet-parent:[unknown-version], C:\dev\Hot
swapAgentExamples\hotswap-agent-examples-servlet-parent\pom.xml, line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.hotswap.examples:seam-hibernate-jsf:[unknown-version] (C:\dev\HotswapAgentExamples\seam-hi
bernate-jsf\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.examples:seam-hibernate-jsf:[unknown-version]: Failure to find org
.hotswap.agent:hotswap-agent-parent:pom:0.2.1-SNAPSHOT in http://snapshots.jboss.org/maven2/ was cached in the local rep
ository, resolution will not be reattempted until the update interval of snapshots.jboss.org has elapsed or updates are
forced and 'parent.relativePath' points at wrong local POM @ line 6, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.hotswap.examples:cdi-hibernate-jsf:[unknown-version] (C:\dev\HotswapAgentExamples\cdi-hibe
rnate-jsf\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.examples:cdi-hibernate-jsf:[unknown-version]: Could not find artif
act org.hotswap.agent:hotswap-agent-parent:pom:0.3.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line
 6, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.hotswap.examples:ejb-cdi-hibernate-jsf:[unknown-version] (C:\dev\HotswapAgentExamples\ejb-
cdi-hibernate-jsf\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hotswap.examples:ejb-cdi-hibernate-jsf:[unknown-version]: Failure to find
org.hotswap.agent:hotswap-agent-parent:pom:0.3.0-SNAPSHOT in https://repository.jboss.org/nexus/content/groups/public/ w
as cached in the local repository, resolution will not be reattempted until the update interval of JBoss Repository has
elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by skybber** [comment]
Upgraded to version 0.3.0
