### ISSUE TITLE
Query on writing custom agent plugin

### ISSUE THREAD

**Issue by tomhillgreyridge** [HotswapProjects/HotswapAgentExamples#70]
Hi there.

I'm investigating writing a custom plugin to allow hot reload of the Javalin framework.  For now, I'm not trying to get anything production ready, just get my head round what is needed, but I'm struggling to get the agent to call my plugin even though it is initialised.

#### General Aim
I have a top level object call App which has a method call "reload".  For now, all I want to do is make it so that if any class is changed, the reload method is called.

#### Setup
Okay.  So I have a top level kotlin object called App

```
package io.javalin.hotswap

import io.javalin.Javalin

object App {
  private val server = Javalin.create()

  fun start(){
    server.start(7777)
    server.get("/",TestClass::home)
  }

  fun stop(){
    server.stop()
  }

  fun reload(){
    stop()
    start()
  }
}

fun main(args: Array<String>){
  App.start()
}
```

that makes reference to another object TestClass

```
package io.javalin.hotswap

import io.javalin.http.Context

object TestClass {
  fun home(ctx: Context){
    ctx.result("Hi there")
  }
}
```
What I want is for a change to TestClass (or any other class) to cause the reload method on App to be called

#### Plugin Implementation
I therefore implemented the following Plugin
```
@Plugin(
  name = "Reload Plugin",
  description = "Testing reload plugin",
  testedVersions = ["unknown"]
)
class ReloadPlugin {
  @OnClassLoadEvent(classNameRegexp = ".*")
  fun onClassReloaded() {
    logger.info("one or more classes reloaded")
  }

  companion object {
    val logger = AgentLogger.getLogger(ReloadPlugin::class.java)

    @JvmStatic
    @OnClassLoadEvent(classNameRegexp = "io.javalin.hotswap.App")
    fun onApplicationStart() {
      logger.info("reload plugin initialised")
      PluginManagerInvoker.buildInitializePlugin(ReloadPlugin::class.java)
    }
  }
}
```

#### Results
When I run the app in debug mode, I see the following
```
HOTSWAP AGENT: 11:59:40.349 DEBUG (org.hotswap.agent.annotation.handler.OnClassLoadedHandler) - Init for method public static final void io.javalin.hotswap.ReloadPlugin.onApplicationStart()
HOTSWAP AGENT: 11:59:40.350 DEBUG (org.hotswap.agent.util.HotswapTransformer) - Registering transformer for class regexp 'io.javalin.hotswap.App'.
HOTSWAP AGENT: 11:59:40.351 DEBUG (org.hotswap.agent.config.PluginRegistry) - Plugin registered class io.javalin.hotswap.ReloadPlugin.
HOTSWAP AGENT: 11:59:40.351 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Reload Plugin]
```

so it correctly finds my plugin.  Then, a little later I see
```
HOTSWAP AGENT: 11:59:40.428 INFO (io.javalin.hotswap.ReloadPlugin) - reload plugin initialised
```

so it is also initialising my plugin.  However, when I change the TestClass and compile I see
```
HOTSWAP AGENT: 12:00:14.067 DEBUG (org.hotswap.agent.plugin.jvm.ClassInitPlugin) - Adding $$ha$clinit to class: io.javalin.hotswap.TestClass
HOTSWAP AGENT: 12:00:14.077 DEBUG (org.hotswap.agent.plugin.jvm.ClassInitPlugin) - Skipping old field INSTANCE
HOTSWAP AGENT: 12:00:14.107 DEBUG (org.hotswap.agent.plugin.jdk.JdkPlugin) - Flushing io.javalin.hotswap.TestClass from com.sun.beans.introspect.ClassInfo cache
HOTSWAP AGENT: 12:00:14.110 DEBUG (org.hotswap.agent.plugin.jdk.JdkPlugin) - Flushing io.javalin.hotswap.TestClass from introspector
HOTSWAP AGENT: 12:00:14.112 TRACE (org.hotswap.agent.plugin.jdk.JdkPlugin) - Removing class from declaredMethodCache.
HOTSWAP AGENT: 12:00:14.112 DEBUG (org.hotswap.agent.plugin.jdk.JdkPlugin) - Flushing io.javalin.hotswap.TestClass from ObjectStreamClass caches
```

so it is indeed redefining the TestClass but my @OnClassLoadEvent is not being called despite having a regexp of ".*".

I tried to follow the custom plugin example but it was using a very old version and referring to annotations which did not exist any more, and when I tried to run a copy to understand it better, it said it was for Java version 5!

If anyone could explain what I'm doing wrong, that would be much appreciated

**Comment by skybber** [comment]
Look at  [howto initialize plugin](https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-myfaces-plugin/src/main/java/org/hotswap/agent/plugin/myfaces/MyFacesPlugin.java#L76), method `buildInitializePlugin` returns javacode that must be injected somewhere (constructor or init method) into javalin main/app/factory class.

**Comment by tomhillgreyridge** [comment]
Okay.  That has worked but I'm not sure why I needed that line!  Given the HotswapAgent has already identified my plugin and called my "onApplicationStart()" method on the load of the io.javalin.hotswap.App class, what does the javacode I add to the constructor actually do?

Is it so that, if the App class is reloaded, my plugin gets re-initialised?

Sorry to ask what is probably a basic question, but I can't find much in the way of documentation of how the process works!  If you can point me in the direction of anything explaining how HotswapAgent plugins work, that would be brilliant.

**Comment by skybber** [comment]
HA registers plugin to app class loader by calling this. Otherwise `onClassReloaded` must be `static`

**Comment by tomhillgreyridge** [comment]
Thanks.  With your help I've managed to get a working custom plugin.  I do have one question about resource changed events but I will put that as a separate issue and close this one
